// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvrxydwedhppmvppqwwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cnh5ZHdlZGhwcG12cHBxd3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDk2MjQsImV4cCI6MjA3NDA4NTYyNH0.PmyU_j94vVwvumJS8GfIHxKPe5ntLUpyqJXzkBEFO_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);